typedef struct node NODE;
typedef struct pilha PILHA;
PILHA* criaPilha();
int vazia(PILHA* pilha);
void push(PILHA* pilha, int valor);
int pop(PILHA* pilha);
int top(PILHA* pilha);
void destroiPilha(PILHA* pilha);
void printPilha(PILHA* pilha);
int busca(PILHA* pilha, int valor);
void buscaRemove1(PILHA* pilha, int valor);
void buscaRemoveTodas(PILHA* pilha, int valor);
void removePares(PILHA* pilha);
void removeImpares(PILHA* pilha);
void removeRepetidos(PILHA* pilha);
